spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Zk19921115.2022
    url: jdbc:mysql://192.168.0.104/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /weshop
